@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class MesBundleFluxAlimentation{

             Bundle.type => [None..None]
             Bundle.entry => [1..None]
             Bundle.entry:mes-observation => [1..1]
             Bundle.entry:mes-observation.resource => [None..None]
             Bundle.entry:mes-observation.request => [1..None]
             Bundle.entry:mes-observation.request.method => [None..None]
             Bundle.entry:mes-observation.request.url => [None..None]
             Bundle.entry:mes-device => [0..1]
             Bundle.entry:mes-device.resource => [None..None]
             Bundle.entry:mes-device.request => [1..None]
             Bundle.entry:mes-device.request.method => [None..None]
             Bundle.entry:mes-device.request.url => [None..None]
        } 

        class MesFrObservationBmi{

             Observation.meta.source => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange.appliesTo => [None..None]
             Observation.referenceRange.appliesTo.coding.system => [1..None]
             Observation.referenceRange.appliesTo.coding.code => [1..None]
        } 

        class MesFrObservationBodyTemperature{

             Observation.meta.source => [None..None]
             Observation.extension:levelOfExertion => <&plus>[None..None]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.value[x] => [None..None]
             Observation.value[x]:valueQuantity => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.bodySite => [None..None]
             Observation.bodySite.coding.system => [1..None]
             Observation.bodySite.coding.code => [1..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesFrObservationBodyWeight{

             Observation.meta.source => [None..None]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.value[x] => [None..None]
             Observation.value[x]:valueQuantity => [None..None]
             Observation.value[x]:valueQuantity.code => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesFrObservationBodyHeight{

             Observation.meta.source => [None..None]
             Observation.extension:bodyposition => <&plus>[None..None]
             Observation.value[x] => [None..None]
             Observation.value[x]:valueQuantity => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesFrObservationBp{

             Observation.meta.source => [None..None]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.subject => [None..None]
             Observation.effective[x] => [None..None]
             Observation.interpretation => [None..None]
             Observation.bodySite => [None..None]
             Observation.bodySite.coding.system => [1..None]
             Observation.bodySite.coding.code => [1..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange.appliesTo => [None..None]
             Observation.referenceRange.appliesTo.coding.system => [1..None]
             Observation.referenceRange.appliesTo.coding.code => [1..None]
        } 

        class MesFrObservationHeartrate{

             Observation.meta.source => [None..None]
             Observation.extension:levelOfExertion => <&plus>[None..None]
             Observation.extension:bodyPosition => <&plus>[None..None]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange.appliesTo => [None..None]
             Observation.referenceRange.appliesTo.coding.system => [1..None]
             Observation.referenceRange.appliesTo.coding.code => [1..None]
        } 

        class MesFrObservationOxygenSat{

             Observation.meta.source => [None..None]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.method => [None..None]
             Observation.method.coding.system => [1..None]
             Observation.method.coding.code => [1..None]
             Observation.device => [None..None]
        } 

        class MesFrObservationRespiratoryRate{

             Observation => [None..None]
             Observation.meta.source => [None..None]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.device => [None..None]
        } 

        class MesObservationGlucose{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement.value[x] => <&plus>[None..None]
             Observation.extension:MesNumberOfDays => <&plus>[0..1]
             Observation.extension:MesDiabetisType => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.code => [None..None]
             Observation.code.coding.system => [1..None]
             Observation.code.coding.code => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.effective[x] => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].value => [None..None]
             Observation.value[x].system => [1..None]
             Observation.value[x].code => [1..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange.appliesTo => [None..None]
             Observation.referenceRange.appliesTo.coding.system => [1..None]
             Observation.referenceRange.appliesTo.coding.code => [1..None]
        } 

        class MesObservationHeadCircumference{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.code.coding:headCircumCode => [1..1]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].value => [1..None]
             Observation.value[x].unit => [1..None]
             Observation.value[x].system => [None..None]
             Observation.value[x].code => [1..None]
        } 

        class MesObservationPainSeverity{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.code.coding => [1..None]
             Observation.code.coding:painServerCode => [1..1]
             Observation.effective[x] => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].unit => [1..None]
             Observation.value[x].system => [None..None]
             Observation.value[x].code => [1..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.bodySite => [None..None]
             Observation.method => [None..None]
        } 

        class MesObservationStepsByDay{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.code.coding:stepsBDCode => [1..1]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].unit => [1..None]
             Observation.value[x].system => [1..None]
             Observation.value[x].code => [1..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesObservationWaistCircumference{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.code.coding:waistCircumCode => [1..1]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].system => [1..None]
             Observation.value[x].code => [1..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.device => [None..None]
         }

     }
     package extension #paleturquoise {

     MesFrObservationBodyTemperature -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesFrObservationBodyWeight -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesFrObservationBp -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesFrObservationBp -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesFrObservationHeartrate -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesFrObservationOxygenSat -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesFrObservationRespiratoryRate -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesObservationGlucose -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesObservationGlucose -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesObservationGlucose -[#black,dashed,thickness=2]-> MesNumberOfDays
     MesObservationGlucose -[#black,dashed,thickness=2]-> MesDiabetisType
     MesObservationHeadCircumference -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesObservationPainSeverity -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesObservationStepsByDay -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesObservationWaistCircumference -[#black,dashed,thickness=2]-> MesReasonForMeasurement

        class MesDiabetisType{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class MesMomentOfMeasurement{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
          Extension.value[x].coding => [None..1]
          Extension.value[x].coding.system => [1..None]
          Extension.value[x].coding.code => [1..None]
        } 
        class MesNumberOfDays{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class MesReasonForMeasurement{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
         }
     }
     package valueset #PaleVioletRed{

        class MethodeGlucoseVS  

     MesObservationGlucose -[#black,dotted,thickness=2]-> MethodeGlucoseVS
       }

package "Ressources de base" #palegreen {

 class "Bundle" as  class94c51f19c37f96ed231f5a0ae512b2a8 

    class94c51f19c37f96ed231f5a0ae512b2a8 --> MesBundleFluxAlimentation

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-observation-bmi" as  class4b43d46c025adbdf652998cf707e8583 

    class4b43d46c025adbdf652998cf707e8583 --> MesFrObservationBmi

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-observation-body-temperature" as  classa4e4b887f7805f0cdd7edd1ed3ba7199 

    classa4e4b887f7805f0cdd7edd1ed3ba7199 --> MesFrObservationBodyTemperature

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-observation-body-weight" as  classc8b21e89ab62ff3d9818309cab0e5443 

    classc8b21e89ab62ff3d9818309cab0e5443 --> MesFrObservationBodyWeight

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-observation-body-height" as  classa7b24c74714e989353d398afa73cd810 

    classa7b24c74714e989353d398afa73cd810 --> MesFrObservationBodyHeight

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-observation-bp" as  class7f705e400ab6436896a90b8831dba724 

    class7f705e400ab6436896a90b8831dba724 --> MesFrObservationBp

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-observation-heartrate" as  class1cf8cb6cc515af65eaab4e2d7c742fc6 

    class1cf8cb6cc515af65eaab4e2d7c742fc6 --> MesFrObservationHeartrate

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-observation-saturation-oxygen" as  class8b0f2e03065f2c5c35b34bc933c17639 

    class8b0f2e03065f2c5c35b34bc933c17639 --> MesFrObservationOxygenSat

 class "https://hl7.fr/ig/fhir/core/StructureDefinition/fr-core-observation-resp-rate" as  class1007bbff74f35a51250cefd06f5f20d7 

    class1007bbff74f35a51250cefd06f5f20d7 --> MesFrObservationRespiratoryRate

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationGlucose

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationHeadCircumference

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationPainSeverity

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationStepsByDay

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationWaistCircumference
}
@enduml